# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# 重投影重采样.py
# Created on: 2023-04-08 20:07:16.00000
#   (generated by ArcGIS/ModelBuilder)
# Description: 
# ---------------------------------------------------------------------------

# Import arcpy module
import arcpy
newenv = r"C:\Users\andwe\Desktop\hurist"

envlist = [newenv]
for env in envlist:
    arcpy.env.workspace = env
    datasets = arcpy.ListRasters()
    for i in datasets:
        # Local variables:
        in_raster = i
        middle_raster = "C:\\Users\\andwe\\Documents\\ArcGIS\\Default.gdb\\P_" + i[0:9]
        out_raster = r"C:\Users\andwe\Desktop\hurist\re_"+i

        # Process: 投影栅格
        arcpy.ProjectRaster_management(in_raster, middle_raster, "PROJCS['WGS_1984_UTM_Zone_49N',GEOGCS['GCS_WGS_1984',DATUM['D_WGS_1984',SPHEROID['WGS_1984',6378137.0,298.257223563]],PRIMEM['Greenwich',0.0],UNIT['Degree',0.0174532925199433]],PROJECTION['Transverse_Mercator'],PARAMETER['False_Easting',500000.0],PARAMETER['False_Northing',0.0],PARAMETER['Central_Meridian',111.0],PARAMETER['Scale_Factor',0.9996],PARAMETER['Latitude_Of_Origin',0.0],UNIT['Meter',1.0]]", "NEAREST", "27.2407540012004 27.2407540012003", "", "", "GEOGCS['GCS_WGS_1984',DATUM['D_WGS_1984',SPHEROID['WGS_1984',6378137.0,298.257223563]],PRIMEM['Greenwich',0.0],UNIT['Degree',0.0174532925199433]]", "NO_VERTICAL")

        # Process: 重采样
        arcpy.Resample_management(middle_raster, out_raster, "300 300", "NEAREST")
        print(i)

